services:
  px4-sitl:
    build:
      context: .
      dockerfile: px4-sitl.Dockerfile
    image: erdemuysalx/px4-sitl:latest
    container_name: px4_sitl 
    privileged: true
    stdin_open: true
    tty: true
    
    volumes:
      - ./ros_ws:/root/ros_ws  
      - ./ros_ws/worlds/default.sdf:/root/PX4-Autopilot/Tools/simulation/gz/worlds/default.sdf

    environment:
      - DISPLAY=:1

    ports:
      - "5901:5901"
      - "6080:6080"
      - "14550:14550/udp"
      - "18570:18570/udp"
    
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s